<?php

/**
 * @file
 * Contains loom_tile_base.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param RouteMatchInterface $route_match
 *
 * @return string
 */
function loom_tile_base_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the loom_tile_base module.
    case 'help.page.loom_tile_base':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('LOOM Tile base module') . '</p>';
      return $output;

    default:
      return '';
  }
}

/**
 * Implements hook_theme().
 */
function loom_tile_base_theme() {
  return [
    'tile' => [
      'render element' => 'elements',
      'template' => 'tile',
    ],
    'tile_content_add_list' => [
      'render element' => 'content',
      'variables' => [
        'content' => NULL
      ],
    ],
  ];
}

function loom_tile_base_theme_suggestions_tile(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#tile'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'tile__' . $sanitized_view_mode;
  $suggestions[] = 'tile__' . $entity->bundle();
  $suggestions[] = 'tile__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'tile__' . $entity->id();
  $suggestions[] = 'tile__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
